Navigation menu not closing when submenu clicked
ReinisZogots/renome-react pull request #1
Opened 2021-12-15 08:38 UTC by ReinisZogots

Have not been able to get my Navigation main menu to close when submenu is selected

2021-12-15 09:39 UTC, VSlobolinskyi commented on src/components/navigation/Navigation.js
> +import { useState } from "react/cjs/react.development";
`from "react"` should work as well

2021-12-15 09:39 UTC, VSlobolinskyi commented on src/components/navigation/buttons/menu/Menu.js
> +import Submenu from "../submenu/Submenu";
Is there a reason to have submenu outside structure.json?

2021-12-15 09:39 UTC, VSlobolinskyi commented on src/components/navigation/buttons/menu/Menu.js
> +  const getMenuItem = (menu, index) => {
`menuItem` maybe?

2021-12-15 09:39 UTC, VSlobolinskyi commented on src/components/navigation/buttons/menu/Menu.js
> +      {dropDown.map((menu, index) => {
Same question here. Aren't you getting `menuItem` not `menu`?

2021-12-15 09:39 UTC, VSlobolinskyi commented on src/components/navigation/buttons/menu/Menu.scss
> +    background-color: var(--white);
Hmm, you are using scss, right. Scss has a different way to declare variables I suggest you look it up

2021-12-15 09:39 UTC, VSlobolinskyi commented on src/components/navigation/buttons/submenu/Submenu.js
> +        <button onClick={() => props.closeSubmenu(false)}>
I suggest you add proptype, so that it would be clear which props you are actually expecting to get.

2021-12-15 10:31 UTC, YuraLeo94 requested changes

2021-12-15 10:31 UTC, YuraLeo94 commented on src/components/navigation/buttons/submenu/Submenu.js
> +      {subDropDown[5].subMenu.map((submenuItem, index) => {
Please remove hard code and do a more generic approach.
Error example:
I wish to add one more item to your menu list and call him "Discounts". This item should be after the "Blog" item. Questions - After these changes, will your application work correctly?

2021-12-15 10:31 UTC, YuraLeo94 commented on src/components/navigation/buttons/submenu/Submenu.scss
> +
Please remove this space

2021-12-15 10:31 UTC, YuraLeo94 commented on src/components/navigation/buttons/menu/Menu.js
> +            {isSubmenu && <Submenu closeSubmenu={isSubmenu=> setIsSubmenu(isSubmenu)}/>}
Please add `subMenu={menu.subMenu}`
And look on this https://en.reactjs.org/docs/components-and-props.html

2021-12-15 10:31 UTC, YuraLeo94 commented on src/components/navigation/buttons/submenu/Submenu.js
> +  const [subDropDown] = useState(Structure.menu);
This doesn't need. You can get all data for `subMenu` from the parent by props

2021-12-15 10:31 UTC, YuraLeo94 commented on src/components/navigation/buttons/menu/Menu.js
> +  const [dropDown] = useState(Structure.menu);
If you call it a menu it will make more sense

2021-12-15 10:31 UTC, YuraLeo94 commented on src/components/navigation/buttons/menu/Menu.js
> +              <a className="menu__section__text" href={dropDown.menu}>{menu.title}</a>
`<a className="menu__section__text" href={dropDown.menu}>{menu.title}</a>`
What do you expect to get from it `href={dropDown.menu}`?
What data is inside the `menu`? (check it and it help you)

2021-12-15 10:33 UTC, YuraLeo94 reviewed
Don't forget to hide the menu :)
![image](https://user-images.githubusercontent.com/71021726/146170587-4bd09213-673d-44fe-93f8-1c77e575783c.png)

2021-12-15 14:06 UTC, ReinisZogots commented on src/components/navigation/Navigation.js
> +        <button onClick={() => [setOpenMenu(!openMenu), setOpenCart(false)]}>
Changed the brackets

2021-12-15 14:06 UTC, ReinisZogots commented on src/components/navigation/Navigation.js
> +        <button onClick={() => [setOpenCart(!openCart), setOpenMenu(false)]}>
changed the brackets

2021-12-15 16:51 UTC, ReinisZogots commented on src/components/navigation/buttons/menu/Menu.scss
> +    background-color: var(--white);
Declared variables in App.scss. added @use "../../../App.css" in every scss file .

2021-12-22 09:31 UTC, ReinisZogots commented on src/components/navigation/buttons/submenu/Submenu.js
> +        <button onClick={() => props.closeSubmenu(false)}>
Added proptypes to Menu and Submenu components

2021-12-22 09:32 UTC, ReinisZogots commented on src/components/navigation/buttons/submenu/Submenu.js
> +      {subDropDown[5].subMenu.map((submenuItem, index) => {
Filtred menu sections, then used the one containing submenu

2021-12-22 09:34 UTC, ReinisZogots commented on src/components/navigation/buttons/submenu/Submenu.js
> +  const [subDropDown] = useState(Structure.menu);
submenu parent is Navigation. Navigation does not have Structure import

2021-12-22 09:37 UTC, ReinisZogots commented on src/components/navigation/buttons/menu/Menu.js
> +              <a className="menu__section__text" href={dropDown.menu}>{menu.title}</a>
changed it

2021-12-22 09:38 UTC, ReinisZogots commented on src/components/navigation/buttons/menu/Menu.js
> +  const [dropDown] = useState(Structure.menu);
used dropdown to avoid having too many "menus"

2021-12-22 09:38 UTC, ReinisZogots commented on src/components/navigation/buttons/menu/Menu.js
> +      {dropDown.map((menu, index) => {
Here i am actually getting menu

2021-12-22 15:25 UTC, Jalal999 commented on src/components/navigation/buttons/menu/index.jsx
>        case "Search":
what if our menu item, which has sublinks, is not called "Features"? Or what if our first menu item is not called Search? will this switch case work?

2021-12-22 15:26 UTC, Jalal999 commented on src/components/navigation/buttons/menu/index.jsx
>        case "Search":
would be better to check if menu item has sublinks with its attribute "isSubMenu, provided in json.

2021-12-22 15:38 UTC, ReinisZogots commented on src/components/navigation/buttons/menu/index.jsx
>        case "Search":
The switch will work but it will not display the search field and search icon for the first menu item and no button for the submenu section item.

2021-12-22 15:42 UTC, Jalal999 commented on src/components/navigation/buttons/menu/index.jsx
>        case "Search":
yes, it will work but not accordingly. instead, it will accept them as a regular menu item and will run default for them.

2021-12-30 07:48 UTC, YuraLeo94 requested changes

2021-12-30 07:48 UTC, YuraLeo94 commented on src/components/navigation/index.jsx
> +      {isMenuOpen === true && <Menu toggleSubMenu = {toggleSubMenu}/>}
Just `isMenuOpen &&` will work the same

2021-12-30 07:48 UTC, YuraLeo94 commented on src/components/navigation/index.jsx
> +          {isMenuOpen === false && (
Just `isMenuOpen &&` will work the same

2021-12-30 07:48 UTC, YuraLeo94 commented on src/components/navigation/index.jsx
> +      {isMenuOpen === true && <Menu toggleSubMenu = {toggleSubMenu}/>}
Same below

2021-12-30 08:01 UTC, YuraLeo94 approved these changes

2021-12-30 08:40 UTC, ReinisZogots commented on src/components/navigation/index.jsx
> +      {isMenuOpen === true && <Menu toggleSubMenu = {toggleSubMenu}/>}
Forgot to remove them, in the previous version I used a string to toggle menu

2022-01-04 08:37 UTC, Jalal999 approved these changes

2022-01-11 20:24 UTC, merged