Feature/carousel
ReinisZogots/renome-react pull request #2
Opened 2022-01-13 10:25 UTC by ReinisZogots

2022-01-13 10:51 UTC, VSlobolinskyi commented on src/components/carousel/slide/Slide.scss
> +  z-index: 8;
I suggest you use bigger increments at least 10

2022-01-13 16:48 UTC, YuraLeo94 requested changes

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +      <div className={`carousel__slide-container`}>
Why  ```className={`carousel__slide-container`}``` not  `className="carousel__slide-container"` ?

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +      <div className={`carousel__slide-container`}>
You need one wrapper for the whole carousel like in the previous [project](https://github.com/ReinisZogots/training-website/blob/master/index.html) look at lines 70 - 98

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +        ))}
You need to render only one slide, then you don't need to use a map.
You need state activeIndex and default he is 0 - first element from an array. `slideData[activeIndex]`

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +    setNewIndex(newIndex - 1);
`setNewIndex(newIndex >0 ? newIndex-1 : lastIndex );`

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +  };
`setNewIndex(newIndex !=  lastIndex ?  newIndex +1 : 0 );`
0 - is fist element from carousel array

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +  const [newIndex, setNewIndex] = useState(0);
Add bellow
`const lastIndex = slideData.length - 1;`

2022-01-13 16:48 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +  }, [newIndex, slideData]);
This all should be in functions prev and next.

2022-01-17 20:50 UTC, ReinisZogots commented on src/components/carousel/index.jsx
> +        ))}
It is required that the slides have sliding animations therefore I use map, because during animation two slides are visible

2022-01-19 11:21 UTC, VSlobolinskyi commented on src/components/carousel/slide/index.jsx
> +    zIndexReduce = " zIndexReduce"
Why do you use string here?

2022-01-19 11:29 UTC, ReinisZogots commented on src/components/carousel/slide/index.jsx
> +    zIndexReduce = " zIndexReduce"
to add class name. Is there a better way?

2022-01-19 11:33 UTC, VSlobolinskyi approved these changes

2022-01-19 11:53 UTC, ReinisZogots commented on src/components/carousel/index.jsx
> +      <div className={`carousel__slide-container`}>
mistake

2022-01-19 14:43 UTC, YuraLeo94 requested changes

2022-01-19 14:43 UTC, YuraLeo94 commented on src/components/carousel/slide/index.jsx
> +      <img src={process.env.PUBLIC_URL + `${path}`} alt={altTag} />
```
let varibale1 = "Hello";
let varibale2 = "World";
className={`carousel__slide ${varibale1} ${varibale2}`}
res->
className="carousel__slide Hello World";
```
**nit:** Please update your `src` and `className`. And `line 28` `zIndexReduce = "zIndexReduce";`

The `nit` is just a minor difference of opinion that doesn't really matter, so you can easily just say you like your way better and resolve the comment.

2022-01-19 14:43 UTC, YuraLeo94 commented on src/components/carousel/index.jsx
> +        ))}
If I add 2 more images to your structure file, will it render only 3 images "active", "prev" and "next", or all five?
![image](https://user-images.githubusercontent.com/71021726/150152825-7e7ee510-e916-4c17-a106-19d9ca45d774.png)
![image](https://user-images.githubusercontent.com/71021726/150153064-5df3d8ff-9024-4892-b09a-f97d9c212d48.png)

```
"carousel": [
    {
      "title": "Made with love",
      "subTitle": "for you",
      "altTag": "eggs and chicken",
      "path": "/assets/img/carousel_img_1.png"
    },
    {
      "title": "Made with hate",
      "subTitle": "for myself",
      "altTag": "something more",
      "path": "/assets/img/carousel_img_2.png"
    },
    {
      "title": "Oranges and laptops",
      "subTitle": "for everyone",
      "altTag": "oranges and laptops",
      "path": "/assets/img/carousel_img_3.png"
    },
    {
      "title": "O2222tops",
      "subTitle": "for everyone",
      "altTag": "oranges and laptops",
      "path": "/assets/img/carousel_img_3.png"
    },
    {
      "title": "Or3333ptops",
      "subTitle": "for everyone",
      "altTag": "oranges and laptops",
      "path": "/assets/img/carousel_img_3.png"
    }
  ]
```

2022-01-20 11:17 UTC, ReinisZogots commented on src/components/carousel/slide/index.jsx
> +      <img src={process.env.PUBLIC_URL + `${path}`} alt={altTag} />
changed to div className={`carousel__slide ${position} ${zIndexReduce}`}>

2022-01-20 15:27 UTC, ReinisZogots commented on src/components/carousel/index.jsx
> +        ))}
Added logic to render only active, previous and next slides.

2022-01-20 17:36 UTC, YuraLeo94 approved these changes

2022-01-20 20:31 UTC, merged